version: 2

secret:
  ignored-paths:
    - .env.example
    - docker-compose.yml

  ignored-matches:
    - name: Local dev postgres default password
      match: postgres
      paths:
        - .env.example
        - docker-compose.yml